services:
  syslog-relay:
    image: ghcr.io/waterstonsltd/cyberalarm-securesensor:stable
    container_name: syslog-relay
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 2g
    mem_reservation: 1g
    cpus: 1
    pids_limit: 100
    volumes:
      - ./data:/var/lib/syslog-relay:rw
    ports:
      - 514:514/udp
      - 514:514/tcp
    environment:
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - StatusEndpoint=${STATUS_ENDPOINT:-https://api-ci-cyberalarm.waterstons.win/api/v1/SyslogRelayStatus}
      - LOGGING__LOGLEVEL__DEFAULT=${LOG_LEVEL:-Information}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"